### ISSUE TITLE
Lower timeout on getLocation + update messaging / UX

### ISSUE THREAD

**Issue by patcon** [dougestey/elsie#88]
Nexus 4 running cyanogenmod 11.
Using CM's built in privacy protection so it may not be getting some permissions related to personal information (it *is* getting location though).

When I started up the app, the first 2 of the top menu buttons didn't seem to have any effect, and only the "info" button shows any sort of feedback. The default search seems to filter correctly when I type, but when I click an option, I just see the UI feedback but no change. A little line animation appears at the top, perhaps signifying loading, but it's not in a style I'm familiar with, and I at first thought it was a visual glitch, as it just kept going forever.

Anyhow, lemme know if you need anything else! I can collect the catlog files if that's useful to you :)

**Comment by dougestey** [comment]
Thanks for this @patcon!

Elsie attempts to get your location before loading a product view. It seems as though she may not be getting one from your device, either due to permissions or a weak GPS signal. I'm going to lower the timeout for that, as I've seen it happen in a couple of cases now. I'm also going to implement a coarser location fallback.

I imagine you've done this already, but have you tried in a variety of places with the same result (indoors/outdoors/etc)?

**Comment by patcon** [comment]
Ah no, I had location off at first, then turned it on, but still no dice. *But* I realized later doing something else that there was no GPS in the basement. So that's likely it. Perhaps just some feedback to show when location isn't yet available and that's holding things up?

**Comment by dougestey** [comment]
Good call. Thanks again for this @patcon, super helpful!

**Comment by patcon** [comment]
Ah ok, so I'm no longer subterranean and check a few different things. All were tried from a fresh start of the app, trying a new product to avoid caching concerns.

- location off: load forever
- device-only location: load forever
- battery-saving: worked perfectly
- high-accuracy: worked perfectly

Also note that when I did go to a location mode that worked, it loaded the page the number of times that I clicked it while loading. nbd, but might want to accommodate that

PS, you are kinda inspiring me to create an app to take a stab at android dev. I've been procrastinating getting into it since the summer, but there's lots I'd love to do!

**Comment by patcon** [comment]
A thought: maybe the "Nearby Availability" section could be the part that loads once location is found?

**Comment by dougestey** [comment]
This is really valuable feedback. I'm gonna push out an update tomorrow and keep you posted. In the meantime it'd be helpful to get you on the beta releases if you're into that!

**Comment by dougestey** [comment]
Fixed in dcee2bec59e3272657d1e8157f869215fe0b699e and 19876723dc7ef7ae34d6fadcc130e8ae082f44db and marked for inclusion in 1.3.

**Comment by patcon** [comment]
Yeah, I'm down! How do i sign up? (My email's on facebook)
